/*====================================================================
  This is a private property of Michael Muniko. You may not distribute
  copy or even hack it, without the permission from Michael Muniko.

  Email: michaelmuniko@gmail.com
  ===================================================================*/
typedef enum
{
	StringNewGame,
	StringLoadGame,
	StringSaveGame,
	StringOptions,
	StringHelp,
	StringCredits,
	StringQuitGame,

	StringWhichEpisode,
	StringEpisode1,
	StringEpisode2,
	StringEpisode3,
	StringEpisode4,

	StringChooseSkill,
	StringSkill1,
	StringSkill2,
	StringSkill3,
	StringSkill4,
	StringSkill5,

	StringDetailHigh,
	StringDetailMedium,
	StringDetailLow,
	StringSoundVolume,
	StringMusicVolume,
	StringEndGame,
	StringScreenSize,
	StringGamma,
	StringMouse,
	StringQuit,
	StringYN,
	StringEndQuestion1,
	StringEndQuestion2,
	StringFairQuestion1,
	StringFairQuestion2,
	StringFairQuestion3,

	StringStone,
	StringStoneBox,
	StringCrystal,
	StringCBox,
	StringHenGrenade,
	StringHenBox,
	StringBattery,
	StringBattBox,

	StringFirstAid,
	StringBread,
	StringMaize,
	StringMeat,
	StringCupcake,
	StringGlass,
	StringBOOM,
	StringMilk,
	StringArmor1,
	StringArmor2,
	StringRepellent,
	StringInvulnerability,
	StringInvisibility,
	StringTorch,
	StringSuit,
	StringMap,
	StringKerzerk,
	StringSpaceBoard,

	StringGotKey1,
	StringGotKey2,
	StringGotKey3,
	StringNeedKey,

	StringFlamer,
	StringDoberwand,
	StringRapid,
	StringLauncher,
	StringCGun,
	StringCannon,
	
	StringTypeCheat,
	StringRobbed,
	StringFullAmmo,
	StringFullArmor,
	StringAllKeys,
	StringUndeadOn,
	StringUndeadOff,
	StringNoClipOn,
	StringNoClipOff,
	StringFullMap,

	StringFoundSecret,
	StringEmptySlot,
	StringSlots,
	StringGameSaved,
	StringGameLoaded,
	StringHighDetail,
	StringMediumDetail,
	StringLowDetail,
	StringGammaLevel0,
	StringGammaLevel1,
	StringGammaLevel2,
	StringGammaLevel3,
	StringGammaLevel4,
	StringGammaLevel5,
	StringGammaLevel6,
	StringGammaLevel7,
	StringGammaLevel8,
	StringFollowModeOFF,
	StringFollowModeON,
	StringAimModeOFF,
	StringAimModeON,
	StringEpisode5,

	StringE1M1,
	StringE1M2,
	StringE1M3,
	StringE1M4,
	StringE1M5,
	StringE1M6,
	StringE1M7,
	StringE1M8,
	StringE1M9,

	StringEndText1,

	StringE2M1,
	StringE2M2,
	StringE2M3,
	StringE2M4,
	StringE2M5,
	StringE2M6,
	StringE2M7,
	StringE2M8,
	StringE2M9,

	StringEndText2,
	
	StringE3M1,
	StringE3M2,
	StringE3M3,
	StringE3M4,
	StringE3M5,
	StringE3M6,
	StringE3M7,
	StringE3M8,
	StringE3M9,

	StringEndText3,

	StringE4M1,
	StringE4M2,
	StringE4M3,
	StringE4M4,
	StringE4M5,
	StringE4M6,
	StringE4M7,
	StringE4M8,
	StringE4M9,

	StringEndText4,

	StringE5M1,
	StringE5M2,
	StringE5M3,
	StringE5M4,
	StringE5M5,
	StringE5M6,
	StringE5M7,
	StringE5M8,
	StringE5M9,

	StringEndText5,

	StringCereal,
	StringSuper,
	StringMusicChange,
	StringMusicNotChanged,

	StringMap01,
	StringMap02,
	StringMap03,
	StringMap04,
	StringMap05,
	StringMap06,
	StringMap07,
	StringMap08,
	StringMap09,
	StringMap10,
	StringMap11,
	StringMap12,
	StringMap13,
	StringMap14,
	StringMap15,
	StringMap16,
	StringMap17,
	StringMap18,
	StringMap19,
	StringMap20,
	StringMap21,
	StringMap22,
	StringMap23,
	StringMap24,
	StringMap25,
	StringMap26,
	StringMap27,
	StringMap28,
	StringMap29,
	StringMap30,
	StringMap31,
	StringMap32,

	StringC1Text,
	StringC2Text,
	StringC3Text,
	StringC4Text,
	StringC5Text,
	StringC6Text,

	CCBoy,
	CCFat,
	CCGirl,
	CCCat,
	CCDog,
	CCBaby,
	CCFlyingFish,
	CCHugeCat,
	CCKnight,
	CCKali,
	CCFatuma,
	CCPlopper,
	CCOgre,
	CCClaratin,
	CCZombieGripper,
	CCClement,
	CCKinene,
	CCBigChui,
	CCShaw,

	NumStrings
} Strings;
